trigger: none

pool:
  vmImage: "ubuntu-latest"

# environment determined by selection at runtime
parameters:
  - name: environment
    displayName: Variable Group
    type: string
    default: WebAppVarsDev
    values:
      - WebAppVarsDev
      - WebAppVarsQA

stages:
  - stage:
    variables:
      - group: ${{ parameters.environment }}
    displayName: "Deploy infrastructure using ${{ parameters.environment }}"
    jobs:
      - job:
        steps:
          - task: AzureCLI@2
            displayName: "Create Resource Group"
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: "az group create --name $(resourceGroupName) --location $(location)"

          - task: AzureCLI@2
            displayName: "Deploy Bicep Template"
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                az deployment group create --resource-group $(resourceGroupName) --template-file infra/paas/bicep/main.bicep --parameters appServiceName=$(appServiceName) appServicePlanName=$(appServicePlanName) location=$(location) envTag=$(envTag) --mode Incremental
